// Code generated by protoc-gen-go. DO NOT EDIT.

package proto

import (
	"context"
)

// MangaRequest represents a request for manga information
type MangaRequest struct {
	ID string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

// MangaResponse represents a manga response
type MangaResponse struct {
	ID       string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Title    string   `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	Author   string   `protobuf:"bytes,3,opt,name=author" json:"author,omitempty"`
	Genres   []string `protobuf:"bytes,4,rep,name=genres" json:"genres,omitempty"`
	Chapters int32    `protobuf:"varint,5,opt,name=chapters" json:"chapters,omitempty"`
	Status   string   `protobuf:"bytes,6,opt,name=status" json:"status,omitempty"`
	Synopsis string   `protobuf:"bytes,7,opt,name=synopsis" json:"synopsis,omitempty"`
}

// SearchRequest represents a search request
type SearchRequest struct {
	Title  string   `protobuf:"bytes,1,opt,name=title" json:"title,omitempty"`
	Author string   `protobuf:"bytes,2,opt,name=author" json:"author,omitempty"`
	Genres []string `protobuf:"bytes,3,rep,name=genres" json:"genres,omitempty"`
	Status string   `protobuf:"bytes,4,opt,name=status" json:"status,omitempty"`
	Limit  int32    `protobuf:"varint,5,opt,name=limit" json:"limit,omitempty"`
}

// SearchResponse represents search results
type SearchResponse struct {
	Results []*MangaResponse `protobuf:"bytes,1,rep,name=results" json:"results,omitempty"`
}

// UpdateProgressRequest represents a progress update
type UpdateProgressRequest struct {
	UserID  string `protobuf:"bytes,1,opt,name=user_id" json:"user_id,omitempty"`
	MangaID string `protobuf:"bytes,2,opt,name=manga_id" json:"manga_id,omitempty"`
	Chapter int32  `protobuf:"varint,3,opt,name=chapter" json:"chapter,omitempty"`
}

// UpdateProgressResponse represents the update response
type UpdateProgressResponse struct {
	Success bool   `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
}

// Top10Response represents top 10 rankings
type Top10Response struct {
	Rankings []*MangaResponse `protobuf:"bytes,1,rep,name=rankings" json:"rankings,omitempty"`
}

// Empty message for requests with no parameters
type Empty struct{}

// MangaServiceServer defines manga service methods
type MangaServiceServer interface {
	GetManga(ctx context.Context, req *MangaRequest) (*MangaResponse, error)
	SearchManga(ctx context.Context, req *SearchRequest) (*SearchResponse, error)
	UpdateProgress(ctx context.Context, req *UpdateProgressRequest) (*UpdateProgressResponse, error)
	GetTop10Manga(ctx context.Context, req *Empty) (*Top10Response, error)
}

// MangaServiceClient defines manga service client methods
type MangaServiceClient interface {
	GetManga(ctx context.Context, req *MangaRequest) (*MangaResponse, error)
	SearchManga(ctx context.Context, req *SearchRequest) (*SearchResponse, error)
	UpdateProgress(ctx context.Context, req *UpdateProgressRequest) (*UpdateProgressResponse, error)
	GetTop10Manga(ctx context.Context, req *Empty) (*Top10Response, error)
}

// UnimplementedMangaServiceServer implements MangaServiceServer
type UnimplementedMangaServiceServer struct{}

func (s *UnimplementedMangaServiceServer) GetManga(ctx context.Context, req *MangaRequest) (*MangaResponse, error) {
	return nil, nil
}

func (s *UnimplementedMangaServiceServer) SearchManga(ctx context.Context, req *SearchRequest) (*SearchResponse, error) {
	return nil, nil
}

func (s *UnimplementedMangaServiceServer) UpdateProgress(ctx context.Context, req *UpdateProgressRequest) (*UpdateProgressResponse, error) {
	return nil, nil
}

func (s *UnimplementedMangaServiceServer) GetTop10Manga(ctx context.Context, req *Empty) (*Top10Response, error) {
	return nil, nil
}

// RegisterMangaServiceServer registers the server implementation
func RegisterMangaServiceServer(s interface{}, srv MangaServiceServer) {
	// gRPC registration would happen here - implement with google.golang.org/grpc if needed
}
