// Code generated by protoc-gen-go. DO NOT EDIT.

package proto

import (
	"context"

	"google.golang.org/grpc"
	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/runtime/protoimpl"
)

// MangaRequest represents a request for manga information
type MangaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *MangaRequest) Reset()         { *x = MangaRequest{} }
func (x *MangaRequest) String() string { return x.ID }
func (*MangaRequest) ProtoMessage()    {}
func (x *MangaRequest) ProtoReflect() protoreflect.Message {
	return nil
}

func (x *MangaRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

// MangaResponse represents a manga response
type MangaResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID       string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title    string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Author   string   `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	Genres   []string `protobuf:"bytes,4,rep,name=genres,proto3" json:"genres,omitempty"`
	Chapters int32    `protobuf:"varint,5,opt,name=chapters,proto3" json:"chapters,omitempty"`
	Status   string   `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Synopsis string   `protobuf:"bytes,7,opt,name=synopsis,proto3" json:"synopsis,omitempty"`
	Rating   float32  `protobuf:"fixed32,8,opt,name=rating,proto3" json:"rating,omitempty"`
}

func (x *MangaResponse) Reset()         { *x = MangaResponse{} }
func (x *MangaResponse) String() string { return x.Title }
func (*MangaResponse) ProtoMessage()    {}
func (x *MangaResponse) ProtoReflect() protoreflect.Message {
	return nil
}

func (x *MangaResponse) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *MangaResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MangaResponse) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *MangaResponse) GetGenres() []string {
	if x != nil {
		return x.Genres
	}
	return nil
}

func (x *MangaResponse) GetChapters() int32 {
	if x != nil {
		return x.Chapters
	}
	return 0
}

func (x *MangaResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *MangaResponse) GetSynopsis() string {
	if x != nil {
		return x.Synopsis
	}
	return ""
}

func (x *MangaResponse) GetRating() float32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

// SearchRequest represents a search request
type SearchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title  string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Author string   `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	Genres []string `protobuf:"bytes,3,rep,name=genres,proto3" json:"genres,omitempty"`
	Status string   `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Limit  int32    `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *SearchRequest) Reset()         { *x = SearchRequest{} }
func (x *SearchRequest) String() string { return x.Title }
func (*SearchRequest) ProtoMessage()    {}
func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	return nil
}

func (x *SearchRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SearchRequest) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *SearchRequest) GetGenres() []string {
	if x != nil {
		return x.Genres
	}
	return nil
}

func (x *SearchRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SearchRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// SearchResponse represents search results
type SearchResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Results []*MangaResponse `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
}

func (x *SearchResponse) Reset()         { *x = SearchResponse{} }
func (x *SearchResponse) String() string { return "SearchResponse" }
func (*SearchResponse) ProtoMessage()    {}
func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	return nil
}

func (x *SearchResponse) GetResults() []*MangaResponse {
	if x != nil {
		return x.Results
	}
	return nil
}

// UpdateProgressRequest represents a progress update
type UpdateProgressRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID  string `protobuf:"bytes,1,opt,name=user_id,proto3" json:"user_id,omitempty"`
	MangaID string `protobuf:"bytes,2,opt,name=manga_id,proto3" json:"manga_id,omitempty"`
	Chapter int32  `protobuf:"varint,3,opt,name=chapter,proto3" json:"chapter,omitempty"`
}

func (x *UpdateProgressRequest) Reset()         { *x = UpdateProgressRequest{} }
func (x *UpdateProgressRequest) String() string { return x.MangaID }
func (*UpdateProgressRequest) ProtoMessage()    {}
func (x *UpdateProgressRequest) ProtoReflect() protoreflect.Message {
	return nil
}

func (x *UpdateProgressRequest) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *UpdateProgressRequest) GetMangaID() string {
	if x != nil {
		return x.MangaID
	}
	return ""
}

func (x *UpdateProgressRequest) GetChapter() int32 {
	if x != nil {
		return x.Chapter
	}
	return 0
}

// UpdateProgressResponse represents the update response
type UpdateProgressResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *UpdateProgressResponse) Reset()         { *x = UpdateProgressResponse{} }
func (x *UpdateProgressResponse) String() string { return x.Message }
func (*UpdateProgressResponse) ProtoMessage()    {}
func (x *UpdateProgressResponse) ProtoReflect() protoreflect.Message {
	return nil
}

func (x *UpdateProgressResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateProgressResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Top10Response represents top 10 rankings
type Top10Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rankings []*MangaResponse `protobuf:"bytes,1,rep,name=rankings,proto3" json:"rankings,omitempty"`
}

func (x *Top10Response) Reset()         { *x = Top10Response{} }
func (x *Top10Response) String() string { return "Top10Response" }
func (*Top10Response) ProtoMessage()    {}
func (x *Top10Response) ProtoReflect() protoreflect.Message {
	return nil
}

func (x *Top10Response) GetRankings() []*MangaResponse {
	if x != nil {
		return x.Rankings
	}
	return nil
}

// Empty message for requests with no parameters
type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset()         { *x = Empty{} }
func (x *Empty) String() string { return "Empty" }
func (*Empty) ProtoMessage()    {}
func (x *Empty) ProtoReflect() protoreflect.Message {
	return nil
}

// MangaServiceServer defines manga service methods
type MangaServiceServer interface {
	GetManga(ctx context.Context, req *MangaRequest) (*MangaResponse, error)
	SearchManga(ctx context.Context, req *SearchRequest) (*SearchResponse, error)
	UpdateProgress(ctx context.Context, req *UpdateProgressRequest) (*UpdateProgressResponse, error)
	GetTop10Manga(ctx context.Context, req *Empty) (*Top10Response, error)
}

// MangaServiceClient defines manga service client methods
type MangaServiceClient interface {
	GetManga(ctx context.Context, req *MangaRequest, opts ...grpc.CallOption) (*MangaResponse, error)
	SearchManga(ctx context.Context, req *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	UpdateProgress(ctx context.Context, req *UpdateProgressRequest, opts ...grpc.CallOption) (*UpdateProgressResponse, error)
	GetTop10Manga(ctx context.Context, req *Empty, opts ...grpc.CallOption) (*Top10Response, error)
}

// mangaServiceClient implements MangaServiceClient
type mangaServiceClient struct {
	cc grpc.ClientConnInterface
}

// NewMangaServiceClient creates a new manga service client
func NewMangaServiceClient(cc grpc.ClientConnInterface) MangaServiceClient {
	return &mangaServiceClient{cc}
}

func (c *mangaServiceClient) GetManga(ctx context.Context, req *MangaRequest, opts ...grpc.CallOption) (*MangaResponse, error) {
	out := new(MangaResponse)
	err := c.cc.Invoke(ctx, "/manga.MangaService/GetManga", req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mangaServiceClient) SearchManga(ctx context.Context, req *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, "/manga.MangaService/SearchManga", req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mangaServiceClient) UpdateProgress(ctx context.Context, req *UpdateProgressRequest, opts ...grpc.CallOption) (*UpdateProgressResponse, error) {
	out := new(UpdateProgressResponse)
	err := c.cc.Invoke(ctx, "/manga.MangaService/UpdateProgress", req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mangaServiceClient) GetTop10Manga(ctx context.Context, req *Empty, opts ...grpc.CallOption) (*Top10Response, error) {
	out := new(Top10Response)
	err := c.cc.Invoke(ctx, "/manga.MangaService/GetTop10Manga", req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UnimplementedMangaServiceServer implements MangaServiceServer
type UnimplementedMangaServiceServer struct{}

func (s *UnimplementedMangaServiceServer) GetManga(ctx context.Context, req *MangaRequest) (*MangaResponse, error) {
	return nil, nil
}

func (s *UnimplementedMangaServiceServer) SearchManga(ctx context.Context, req *SearchRequest) (*SearchResponse, error) {
	return nil, nil
}

func (s *UnimplementedMangaServiceServer) UpdateProgress(ctx context.Context, req *UpdateProgressRequest) (*UpdateProgressResponse, error) {
	return nil, nil
}

func (s *UnimplementedMangaServiceServer) GetTop10Manga(ctx context.Context, req *Empty) (*Top10Response, error) {
	return nil, nil
}

// MangaService_ServiceDesc is the service descriptor for MangaService
var MangaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "manga.MangaService",
	HandlerType: (*MangaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetManga",
			Handler:    _MangaService_GetManga_Handler,
		},
		{
			MethodName: "SearchManga",
			Handler:    _MangaService_SearchManga_Handler,
		},
		{
			MethodName: "UpdateProgress",
			Handler:    _MangaService_UpdateProgress_Handler,
		},
		{
			MethodName: "GetTop10Manga",
			Handler:    _MangaService_GetTop10Manga_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "manga.proto",
}

func _MangaService_GetManga_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MangaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MangaServiceServer).GetManga(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/manga.MangaService/GetManga",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MangaServiceServer).GetManga(ctx, req.(*MangaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MangaService_SearchManga_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MangaServiceServer).SearchManga(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/manga.MangaService/SearchManga",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MangaServiceServer).SearchManga(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MangaService_UpdateProgress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProgressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MangaServiceServer).UpdateProgress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/manga.MangaService/UpdateProgress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MangaServiceServer).UpdateProgress(ctx, req.(*UpdateProgressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MangaService_GetTop10Manga_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MangaServiceServer).GetTop10Manga(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/manga.MangaService/GetTop10Manga",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MangaServiceServer).GetTop10Manga(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// RegisterMangaServiceServer registers the server implementation
func RegisterMangaServiceServer(s grpc.ServiceRegistrar, srv MangaServiceServer) {
	s.RegisterService(&MangaService_ServiceDesc, srv)
}
